project_id = "tdjtumtdkjicnhlpqqzd"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[functions.analyze-verse]
verify_jwt = false

[functions.jeeves]
verify_jwt = false

[functions.analyze-critic-video]
verify_jwt = true

[functions.daily-content-generator]
verify_jwt = false

[functions.generate-monthly-games]
verify_jwt = false

[functions.verify-student]
verify_jwt = true

[functions.analyze-quarterly-lesson]
verify_jwt = false

[functions.generate-access-code]
verify_jwt = true
